name: pr

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run npm lint
              run: |
                  npm install
                  cd packages/backend && npm install
                  cd ../frontend && npm install
                  cd ../..
                  npm run lint
